export const PWA_KIT_BOT_USER_SESSION = 'pwa-kit-bot-user-session'
export const GITHUB_ACTIONS_E2E_SESSION = 'github-actions-e2e-session'
export const CI_AVAILABILITY_AVAILABLE = 'available'
export const CI_AVAILABILITY_IN_USE = 'in-use'
export const ACQUIRE_TARGET_STATUS_SUCCESS = 'ACQUIRE_TARGET_SUCCESS'
export const ACQUIRE_TARGET_STATUS_FAILED = 'ACQUIRE_TARGET_FAILED'

export const AWS_ACCESS_READ_ONLY = 'READ-ONLY'
export const AWS_ACCESS_READ_WRITE = 'READ-WRITE'
export const AWS_S3_ERR_NO_SUCH_KEY = 'NoSuchKey'
export const AWS_S3_ERR_PRECONDITION_FAILED = 'PreconditionFailedException'
