name: setup_ubuntu
inputs:
  cwd:
    required: false
    default: ${{ github.workspace }}
description: "Setup Ubuntu Machine"
runs:
  using: composite
  steps:
    - name: Install Dependencies
      working-directory: ${{ inputs.cwd }}
      run: |-
        # Install node dependencies
        set -e
        npm cache clean --force
        echo "HEY ABOUT TO RUN THIS"
        node ./scripts/gtime.js monorepo_install npm ci --verbose
        echo "RAN IT"

        # Build the PWA
        # npm run lerna -- run analyze-build --scope "@salesforce/retail-react-app"

        # Report bundle sizes
        # node ./scripts/report-bundle-size.js

        # Install Snyk CLI
        # TODO: Ticket W-12425059. Revisit Snyk CLI integration to monitor manifest files on generated projects.
        # TODO: Latest Snyk CLI version is currently failing on npm i. We use the alternative Snyk GitHub integration.
        # sudo npm install -g snyk

        # Install Lighthouse CI CLI
        sudo npm install -g @lhci/cli
      shell: bash
