name: 'Changelog Check'
description: 'Check if changelog is updated for the changed packages'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history to access all commits

    - name: Force exit 0
      id: get_base_sha
      run: |
        exit 0
      shell: bash

