name: SalesforceCommerceCloud/pwa-kit/bug_bounty
on:
  push:
    branches:
      - 'mrt-test-ci-deploy'

jobs:
  deploy-bug-bounty:
    runs-on: ubuntu-latest
    steps:
      - name: Check if latest release
        id: release
        run: |
          RELEASE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")

          LATEST_TAG_NAME=$(echo "$RELEASE_JSON" | jq -r '.tag_name')
          RELEASE_EVENT_TAG_NAME=$(echo ${{ github.event.release.tag_name }})

          if [ "$LATEST_TAG_NAME" = "$RELEASE_EVENT_TAG_NAME" ]; then
            echo "IS_LATEST_RELEASE=true" >> $GITHUB_ENV
          else
            echo "IS_LATEST_RELEASE=false" >> $GITHUB_ENV
          fi

          echo "Latest tag: $LATEST_TAG_NAME"
          echo "Release event tag: $RELEASE_EVENT_TAG_NAME"
          echo $IS_LATEST_RELEASE
          echo "Is latest release: ${{ env.IS_LATEST_RELEASE }}"

